language: sh

branches:
  only:
    - main

os:
  - linux
  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-setuptools python3-pip python3-sphinx
  - sudo apt-get install -y clang doxygen make
  - sudo apt-get remove --purge --auto-remove cmake
  - sudo apt-get purge --auto-remove cmake
  - sudo mkdir /opt/cmake
  - sudo wget https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-Linux-x86_64.sh
  - sudo sh cmake-3.17.2-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
  - pip3 install themata

script:
  - cd ./docs/ 
  - bash ./make.sh
  - cd ../test/
  - /opt/cmake/bin/cmake CMakeLists.txt -G"Unix Makefiles"
  - make
  - cd ../
  
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./docs/deploy.sh
    on:
       branch: main
