language: sh

branches:
  only:
  - master

os:
  - linux
  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip python3-sphinx
  - sudo apt-get install -y cmake clang doxygen make

script:
  - cd ./docs/ 
  - bash ./make.sh
  - cd ../test/
  - cmake CMakeLists.txt -G"Unix Makefiles"
  - make
  - cd build/
  - ls
  - cd ../
  - cd ../
  
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./docs/deploy.sh
    on:
       branch: master
