
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest, windows-latest]
        platform: [x86, x64]
        compiler: [gnu, clang]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Exotic Libraries
        uses: exoticlibraries/exotic-action@master
        with:
          run-cester-regression: false
        
      - name: Run Regression
        uses: exoticlibraries/exotic-action@master
        with:
          download-exotic-libraries: false
          test-folders: |
            test/
          test-exclude-file-pattern:  |
            mock+
            crash_test.c
            test_assert_double_float+
            test_assert_long_long+
            test_shared_data+
          test-exclude-file-pattern-macos:  |
            test_expect_actual
            test_junitxml_output
            test_junitxml_output_no_time
            test_tap_output
            test_tap_output_no_time
            test_tap_v13_output
            test_tap_v13_output_no_time
            
        
