
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        platform: [x86, x64]
        compiler: [gnu, clang]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Regression
        uses: exoticlibraries/exotic-action@v1.1
        with:
          download-exotic-libraries: false
          run-regression: true
          test-folders: |
            test/
          test-exclude-file-pattern: |
            mock+
            crash_test.c
            test_assert_double_float+
            test_assert_long_long+
          compiler-options-for-tests: |
            -I../include -I./include
          regression-cli-options: |
            --cester-printversion
            
        
